version: "3"
services:
  cset:
    build: 
      context: ./CSETWebApi/CSETWeb_Api
      dockerfile: Dockerfile.api
    ports: 
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mssql
  reports:
    build: 
      context: ./CSETWebApi/CSETWeb_Api
      dockerfile: Dockerfile.reports
    ports:
      - "44363:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - cset
  mssql:
    build: ./Database Scripts/docker
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=CSET-Developer22
        - MSSQL_PID=Express
    ports:
      - "1433:1433"