version: "3"
services:
  angular:
    build: ./CSETWebNg
    ports: 
      - "4200:4200"
    command: 'node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve --configuration=docker --host 0.0.0.0'
    depends_on:
      - cset
  cset:
    build: ./CSETWebApi/CSETWeb_Api/
    ports: 
      - "5000:5000"
      - "5001:5001"
    command: 'dotnet run --launch-profile=Docker --project ./CSETWeb_ApiCore'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - "./CSETWebApi/CSETWeb_Api:/app"
    depends_on:
      - mssql
  mssql:
    build: ./Database Scripts/docker
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=CSET-Developer22
        - MSSQL_PID=Express
    ports:
      - "1433:1433"
