version: "3"
services:
  cset:
    build: ./CSETWebApi/CSETWeb_Api/
    ports: 
      - "5000:80"
      - "44363:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mssql
  mssql:
    build: ./Database Scripts/docker
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=CSET-Developer22
        - MSSQL_PID=Express
    ports:
      - "1433:1433"
